import { Node, Scope, TypeGuards } from 'ts-simple-ast';
import * as ts from 'typescript';
import { CodeFix, CodeFixOptions } from '../codeFixes';
import { getKindName } from 'typescript-ast-util';

export const codeFixCreateConstructor: CodeFix = {
  name: 'Declare constructor',
  config: { variableType: 'const' },
  
  predicate: (arg: CodeFixOptions) => {

    if (!arg.diagnostics.find(d=>d.code === 2554)) {
      return false
    }
    if (arg.containingTarget.kind === ts.SyntaxKind.NewExpression) {
      return true
    } else {
      arg.log(`codeFixCreateConstructor predicate false because  child.kind didn't match : child.kind==${getKindName(arg.containingTarget.kind)}, child.parent.kind==${getKindName(arg.containingTarget.parent.kind)}`)
      return false
    }
  },

  description: (arg: CodeFixOptions): string => `Declare constructor "${arg.containingTarget.getText()}"`,

  apply: (arg: CodeFixOptions) => {
    const originalKind = arg.simpleNode.getKind()
    if (!TypeGuards.isNewExpression(arg.simpleNode)) {
      arg.simpleNode = arg.simpleNode.getFirstAncestorByKind(ts.SyntaxKind.NewExpression)
    }
    if (!arg.simpleNode || !TypeGuards.isNewExpression(arg.simpleNode)) {
      arg.log(`codeFixCreateConstructor apply fail because couldnt find a NewExpression from arg.simpleNode returned by sourcefile..getDescendantAtPos(positionOrRangeToNumber(positionOrRange) - returned arg.simpleNode kind was ${getKindName(originalKind)}`)
      return
    }
    const argTypes = arg.simpleNode.getArguments().map(arg => arg.getType().getApparentType().getText())
    const classDeclaration = arg.simpleNode.getExpression().getSymbol()!.getDeclarations()[0]
    if (TypeGuards.isClassDeclaration(classDeclaration)) {
      classDeclaration.addConstructor({
        // docs: 'Autogenerated constructor', //TODO. add some jsdoc to generated constructor
        scope: Scope.Public,
        parameters: argTypes.map(type => ({
          name: `a${type.substring(0, 1).toUpperCase()}${type.substring(1, type.length)}`,
          hasQuestionToken: false,
          type,
          isRestParameter: false,
          // scope: Scope.,
        })
        )
      })
    } else {
      arg.log(`codeFixCreateConstructor apply fail because arg.simpleNode is not ClassDeclaration is ${getKindName(classDeclaration.getKind())}`)
    }
  }
};
