export { Project, ts } from 'ts-morph'
export * from './astPath'
export * from './changes'
export * from './compilerOptions'
export * from './declaration'
export * from './diagnostics'
export * from './flags'
export * from './generalNode'
export * from './locals'
export * from './modify'
export * from './node'
export * from './path'
export * from './refactor'
export * from './reference'
export * from './types'
export { tsMorph }

import * as tsMorph from 'ts-morph'
