class Apple {
    /**
     * TODO: Document this autogenerated constructor
     */
    public constructor(aString0: String) {
        throw new Error('Not implemented');
    }
}

let fso=2

function a(d){
  let apple=new Apple('red')
}

let ffdfdf;
a(ffdfdf)

